/*
 * Dio_Lcfg.c
 *
 *  Created on: Jan 16, 2021
 *      Author: future
 */
#include "Dio.h"
#include "Dio_Cfg.h"

#define DIO_CHANNEL_DIR_INPUT  0
#define DIO_CHANNEL_DIR_OUTPUT  1



const Dio_CfgUnionType DioCfgUnion ={
		{
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_A0_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_A1_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_A2_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_A3_DIRECTION*/
				DIO_CHANNEL_DIR_OUTPUT, /*DIO_CHANNEL_A4_DIRECTION*/
				DIO_CHANNEL_DIR_OUTPUT, /*DIO_CHANNEL_A5_DIRECTION*/
				DIO_CHANNEL_DIR_OUTPUT, /*DIO_CHANNEL_A6_DIRECTION*/
				DIO_CHANNEL_DIR_OUTPUT, /*DIO_CHANNEL_A7_DIRECTION*/

				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_B0_DIRECTION*/
				DIO_CHANNEL_DIR_OUTPUT, /*DIO_CHANNEL_B1_DIRECTION*/
				DIO_CHANNEL_DIR_OUTPUT, /*DIO_CHANNEL_B2_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_B3_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_B4_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_B5_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_B6_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_B7_DIRECTION*/

				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_C0_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_C1_DIRECTION*/
				DIO_CHANNEL_DIR_OUTPUT, /*DIO_CHANNEL_C2_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_C3_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_C4_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_C5_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_C6_DIRECTION*/
				DIO_CHANNEL_DIR_OUTPUT, /*DIO_CHANNEL_C7_DIRECTION*/

				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_D0_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_D1_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_D2_DIRECTION*/
				DIO_CHANNEL_DIR_OUTPUT, /*DIO_CHANNEL_D3_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_D4_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_D5_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT, /*DIO_CHANNEL_D6_DIRECTION*/
				DIO_CHANNEL_DIR_INPUT /*DIO_CHANNEL_D7_DIRECTION*/
		}
};

/*please add channel to be attached to internal pullup resistors*/
Dio_ChannelType InternalPullUpCfgChannels[NUM_OF_ATTACHED_CHANNELS] = {
		Dio_Channel_A0,
		Dio_Channel_B3,
		Dio_Channel_C6

};
